[colors.primary]
background = "#000000"
foreground = "#FFFFFF" # This sets the text color to white for contrast

[font]
normal = { family = "Noto Sans Mono", style = "Regular" }
bold = { family = "Noto Sans Mono", style = "Bold" }
italic = { family = "Noto Sans Mono", style = "Italic" }
bold_italic = { family = "Noto Sans Mono", style = "Bold Italic" }
size = 11.0 # You can adjust this size as needed
